resources:
  repositories:
    - repository: self
      clean: true
    - repository: yaml-pipeline-templates
      type: git
      name: dx-yaml-pipeline-templates
      ref: master

trigger:
  paths:
    include:
      - '*'

pool:
  name: nwo-build-agents
  demands: maven

extends:
  template: build.yaml@yaml-pipeline-templates
  parameters:
    buildSteps:
      - template: build-legacy.yaml
    buildForBranches:
      - refs/heads/release
      - refs/heads/feature
      - refs/pull
