resources:
  repositories:
  - repository: yaml-pipeline-templates
    type: git
    name: dx-yaml-pipeline-templates
    ref: master
  pipelines:
  - pipeline: service
    source: \pace\infra\dx-systems-performance-infra
    branch: master

trigger:
  branches:
    exclude:
    - '*'

schedules:
  - cron: "00 02 * * Mon-Fri,Sun"
    displayName: Deploy to keep environments up to date with latest changes
    branches:
      include:
        - master
    always: false # Only run if there have been changes since last scheduled run

pool:
  name: pat-2-release-agents

extends:
  template: release.yaml@yaml-pipeline-templates
  parameters:
    releaseProfile: dev-environments
    additionalEnvironments:
      - cicd/shared-custom-environment-list.yaml@self
    deploymentProfile: infrastructure-only
    servicePrefix: dx
    serviceName: systems-performance-infra
    useVariableGroups: false
    variableTemplates:
      - cicd/variables/common.yaml